version: '1.0'

services:
    web:
        build: .
        ports:
            - "8000:8000"
        depends_on:
            - postgres
    postgres:
        image: postgres:16.0
        environment:
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'password'
            POSTGRES_DB: 'booking_db'
        ports:
            - "5432:5432"
