# Generated by Django 5.0.3 on 2024-04-04 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_customuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_login',
        ),
    ]
