# Generated by Django 5.0.3 on 2024-04-12 13:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_slot_options_remove_slot_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='payment_image',
            field=models.ImageField(upload_to='media/payment_images/'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='request_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
