# Generated by Django 5.0.3 on 2024-04-12 13:23

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_slot_payment_image_alter_slot_request_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='payment_image',
            field=models.ImageField(upload_to=booking.models.Slot.payment_image_path),
        ),
    ]
