# Generated by Django 5.0.3 on 2024-04-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_deletedslot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deletedslot',
            options={'ordering': ['deletiontime'], 'verbose_name': 'Deleted Slot', 'verbose_name_plural': 'Deleted Slots'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
